### ISSUE TITLE
Add possibility to easily check values in dropdownlist

### ISSUE THREAD

**Issue by sandrabn** [TheSoftwareHouse/Kakunin#149]
A step like "Then the available values for 'e:dropdownlist' are  'value1, value2, value3' " would come in really handy, expecially when the dropdownlist consists of a lot of values. 
Now i have to use "And there is element 'dropdownListitem1' with value 't:value1'". This results in very long scenarios and I have to define a new page object for every single value.

**Comment by sethii** [comment]
Just to clarify, you need to check if options of given dropdown (let's say a dropdown defined in page object as "someDropDown") are exact like "value1, value2, value3" yep?

It shouldn't be hard to add something like this. We would have to define selector for options (probably $$('.my-select option') and then just check if every option defined by value1, etc was found.

I would use table syntax for it, so instead of "value1, value2" I would go with 
```
| value 1 |
| value 2|
```

**Comment by sandrabn** [comment]
Yes, that's exactly what I need to do. The table syntax would indeed work great for this. 

Would it be possible to add a check to see if the number op options in the html match the number of options in the table from the scenario? To make sure no extra options have been added to the dropdownlist.

**Comment by sethii** [comment]
Yep, this should not be a problem at all.

**Comment by simonsipl** [comment]
It is available and working on "next" branch @sandrabn, will be introduced in 3.0

**Comment by sandrabn** [comment]
Great, thanks!

**Comment by sethii** [comment]
@sandrabn we've just published a new version with a feature you requested 3.0.0

**Comment by sandrabn** [comment]
Awesome, thanks!
